name: Build and push to DockerHub

on:
  push:
    branches:
      - prod
    paths-ignore:
      - ".github/workflows/**"

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [ubuntu-latest]
          architecture: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ""
          driver: docker-container
          endpoint: ""
          platforms: linux/amd64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: tecsci/plant-report
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-n-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [ubuntu-latest]
          architecture: [amd64]

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git -C /etc/RELATORIO-USINA/ fetch --all
            git -C /etc/RELATORIO-USINA/ switch prod
            git -C /etc/RELATORIO-USINA/ pull
            docker-compose -f /etc/RELATORIO-USINA/docker-compose.yaml pull
            docker-compose -f /etc/RELATORIO-USINA/docker-compose.yaml up -d --force-recreate
